// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOperation creates a new instance of MockOperation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOperation(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOperation {
	mock := &MockOperation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOperation is an autogenerated mock type for the Operation type
type MockOperation struct {
	mock.Mock
}

type MockOperation_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOperation) EXPECT() *MockOperation_Expecter {
	return &MockOperation_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockOperation
func (_mock *MockOperation) Delete(ctx context.Context, userName string, text string, all bool) error {
	ret := _mock.Called(ctx, userName, text, all)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool) error); ok {
		r0 = returnFunc(ctx, userName, text, all)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOperation_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockOperation_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userName string
//   - text string
//   - all bool
func (_e *MockOperation_Expecter) Delete(ctx interface{}, userName interface{}, text interface{}, all interface{}) *MockOperation_Delete_Call {
	return &MockOperation_Delete_Call{Call: _e.mock.On("Delete", ctx, userName, text, all)}
}

func (_c *MockOperation_Delete_Call) Run(run func(ctx context.Context, userName string, text string, all bool)) *MockOperation_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOperation_Delete_Call) Return(err error) *MockOperation_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOperation_Delete_Call) RunAndReturn(run func(ctx context.Context, userName string, text string, all bool) error) *MockOperation_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Extract provides a mock function for the type MockOperation
func (_mock *MockOperation) Extract(ctx context.Context, userName string, cnt int) ([]string, error) {
	ret := _mock.Called(ctx, userName, cnt)

	if len(ret) == 0 {
		panic("no return value specified for Extract")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) ([]string, error)); ok {
		return returnFunc(ctx, userName, cnt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) []string); ok {
		r0 = returnFunc(ctx, userName, cnt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, userName, cnt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperation_Extract_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Extract'
type MockOperation_Extract_Call struct {
	*mock.Call
}

// Extract is a helper method to define mock.On call
//   - ctx context.Context
//   - userName string
//   - cnt int
func (_e *MockOperation_Expecter) Extract(ctx interface{}, userName interface{}, cnt interface{}) *MockOperation_Extract_Call {
	return &MockOperation_Extract_Call{Call: _e.mock.On("Extract", ctx, userName, cnt)}
}

func (_c *MockOperation_Extract_Call) Run(run func(ctx context.Context, userName string, cnt int)) *MockOperation_Extract_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOperation_Extract_Call) Return(strings []string, err error) *MockOperation_Extract_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockOperation_Extract_Call) RunAndReturn(run func(ctx context.Context, userName string, cnt int) ([]string, error)) *MockOperation_Extract_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockOperation
func (_mock *MockOperation) Save(ctx context.Context, text string, userName string) error {
	ret := _mock.Called(ctx, text, userName)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, text, userName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOperation_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockOperation_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
//   - userName string
func (_e *MockOperation_Expecter) Save(ctx interface{}, text interface{}, userName interface{}) *MockOperation_Save_Call {
	return &MockOperation_Save_Call{Call: _e.mock.On("Save", ctx, text, userName)}
}

func (_c *MockOperation_Save_Call) Run(run func(ctx context.Context, text string, userName string)) *MockOperation_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOperation_Save_Call) Return(err error) *MockOperation_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOperation_Save_Call) RunAndReturn(run func(ctx context.Context, text string, userName string) error) *MockOperation_Save_Call {
	_c.Call.Return(run)
	return _c
}
