// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"bot/internal/clients/tgclient"

	mock "github.com/stretchr/testify/mock"
)

// NewMockReciver creates a new instance of MockReciver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReciver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReciver {
	mock := &MockReciver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReciver is an autogenerated mock type for the Reciver type
type MockReciver struct {
	mock.Mock
}

type MockReciver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReciver) EXPECT() *MockReciver_Expecter {
	return &MockReciver_Expecter{mock: &_m.Mock}
}

// Updates provides a mock function for the type MockReciver
func (_mock *MockReciver) Updates(limit int, offset int) ([]tgclient.Update, error) {
	ret := _mock.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for Updates")
	}

	var r0 []tgclient.Update
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, int) ([]tgclient.Update, error)); ok {
		return returnFunc(limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int) []tgclient.Update); ok {
		r0 = returnFunc(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tgclient.Update)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = returnFunc(limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReciver_Updates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Updates'
type MockReciver_Updates_Call struct {
	*mock.Call
}

// Updates is a helper method to define mock.On call
//   - limit int
//   - offset int
func (_e *MockReciver_Expecter) Updates(limit interface{}, offset interface{}) *MockReciver_Updates_Call {
	return &MockReciver_Updates_Call{Call: _e.mock.On("Updates", limit, offset)}
}

func (_c *MockReciver_Updates_Call) Run(run func(limit int, offset int)) *MockReciver_Updates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReciver_Updates_Call) Return(updates []tgclient.Update, err error) *MockReciver_Updates_Call {
	_c.Call.Return(updates, err)
	return _c
}

func (_c *MockReciver_Updates_Call) RunAndReturn(run func(limit int, offset int) ([]tgclient.Update, error)) *MockReciver_Updates_Call {
	_c.Call.Return(run)
	return _c
}
