// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSender creates a new instance of MockSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSender {
	mock := &MockSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSender is an autogenerated mock type for the Sender type
type MockSender struct {
	mock.Mock
}

type MockSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSender) EXPECT() *MockSender_Expecter {
	return &MockSender_Expecter{mock: &_m.Mock}
}

// SendMessage provides a mock function for the type MockSender
func (_mock *MockSender) SendMessage(chatID int, text string) error {
	ret := _mock.Called(chatID, text)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, string) error); ok {
		r0 = returnFunc(chatID, text)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSender_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockSender_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - chatID int
//   - text string
func (_e *MockSender_Expecter) SendMessage(chatID interface{}, text interface{}) *MockSender_SendMessage_Call {
	return &MockSender_SendMessage_Call{Call: _e.mock.On("SendMessage", chatID, text)}
}

func (_c *MockSender_SendMessage_Call) Run(run func(chatID int, text string)) *MockSender_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSender_SendMessage_Call) Return(err error) *MockSender_SendMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSender_SendMessage_Call) RunAndReturn(run func(chatID int, text string) error) *MockSender_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}
